- Business Law
- Small Business Law
- Contracts
- Non-profit corporations
- Articles of Incorporation/By-Laws
- Professional Responsibility/Ethics
- Dispute Resolution/Negotiations
- Landlord/Tenant
- Trusts and Estates
- Education Law
- Law Practice Management
- LGBTQ Issues
